{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-sidecar-tls
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca: 
{{ .Values.tls.ca | b64enc }}
  cert: 
{{ .Values.tls.cert | b64enc }}
  key: 
{{ .Values.tls.key | b64enc }}
{{- end }} 