apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-npd
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Chart.Version }}
    spec:
      containers:
        - name: node-problem-detector
          command:
            - /node-problem-detector
            - --logtostderr
            - --apiserver-wait-timeout=10s
            - --config.system-log-monitor={{ .Values.systemLog }}
            - --config.system-stats-monitor={{ .Values.systemStats }}
            - --prometheus-address=0.0.0.0
            - --address=0.0.0.0
          {{- range .Values.extraArgs }}
            - {{ . }}
          {{- end }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: prometheus
              containerPort: 20257
              protocol: TCP
            - name: kubernetes
              containerPort: 20256
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: log
              mountPath: /run/log
              readOnly: true
            - name: kmsg
              mountPath: /dev/kmsg
              readOnly: true
            # Make sure node problem detector is in the same timezone
            # with the host.
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: npd-config
              mountPath: /config/npd
              readOnly: true
  {{- if and .Values.resources .Values.resources.core }}
          resources:
{{ toYaml .Values.resources.core | indent 12 }}
{{- end }}
{{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
{{- end }}
      volumes:
        - name: log
          # Config `log` to your system log directory
          hostPath:
            path: /run/log/
        - name: kmsg
          hostPath:
            path: /dev/kmsg
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: npd-config
          configMap:
            name: {{ .Release.Name }}-npd
      serviceAccount: {{ .Release.Name }}-npd
