global:
  cattle:
    systemDefaultRegistry: ""

ackOperator:
  image:
    repository: wangsiye/ack-operator
    tag: v2.13.3-ent  

httpProxy: ""
httpsProxy: ""
noProxy: ""
additionalTrustedCAs: false
leaderElect: true
lockName: ""
lockNamespace: ""
qps: ""
burst: ""
